#define PRODUCT_NAME			"OpenVPNAS"
#define PRODUCT_VERSION			"9.9.2"
#define PRODUCT_VERSION_RESOURCE	9,0,0,9
#define PRODUCT_TAP_WIN_COMPONENT_ID	"tapoas"
#define PRODUCT_TAP_WIN_MAJOR		9
#define PRODUCT_TAP_WIN_MINOR		9
#define PRODUCT_TAP_WIN_PROVIDER		"TAP-Win32 Provider OAS"
#define PRODUCT_TAP_WIN_DEVICE_DESCRIPTION	"TAP-Win32 Adapter OAS (NDIS 6.0)"
#define PRODUCT_TAP_WIN_RELDATE		"07/15/2013"
